spring.application.name=authentication

spring.datasource.url=jdbc:postgresql://localhost:5432/auth
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update

#kafka.enabled=true
#kafka.bootstrap-servers=kafka:9092  # ???????? ? localhost ?? kafka
#kafka.consumer.group-id=BANK.deleted_tokens

jwt.secret=12345678qwertyui12345678qwertyui12345678qwertyui
jwt.expiration=3600000

user-service.host=51.250.33.133
user-service.port=8082
